[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "gymnasium_mars_lander"
version = "1.0.0"
authors = [
    { name = "Quentin Deschamps", email = "quentindeschamps18@gmail.com" },
]
description = "A reinforcement learning environment for the Mars Lander CG puzzle"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["Reinforcement Learning", "game", "RL", "AI", "gymnasium", "pygame"]
license = { text = "MIT" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Games/Entertainment",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "gymnasium==1.3.0",
    "pygame==2.6.1",
]

[project.optional-dependencies]
training = [
    "matplotlib==3.11.1",
    "moviepy==2.2.1",
    "rl-zoo3==2.9.1",
    "tensorboard==2.21.0",
]
testing = ["pytest"]
quality = ["ruff", "ty"]

[project.urls]
Repository = "https://github.com/Quentin18/gymnasium-mars-lander"

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = [
    "I", # isort
    "PL", # pylint
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
