gymnasium_mars_lander/MarsLander-v0:
  n_envs: 1
  policy: 'MultiInputPolicy'
  n_timesteps: !!float 1e6
  n_steps: 8192
  gamma: 0.995
  learning_rate: 0.000005
  ent_coef: 0.0005
  use_sde: True
  sde_sample_freq: 4
  max_grad_norm: 0.2
  vf_coef: 0.25
  policy_kwargs: "dict(
    log_std_init=-2,
    ortho_init=False,
    activation_fn=nn.ReLU,
    net_arch=dict(pi=[128, 128], vf=[128, 128])
  )"
  callback:
    - wandb.integration.sb3.WandbCallback:
        gradient_save_freq: 10000
        model_save_freq: 100000
        model_save_path: "models/PPO"
